import "babel-polyfill";
import {const_fun} from './components/constants.js';
import {scope_fun} from './components/scope.js';
import {enhance_fun} from './components/enhance_obj.js';
import {arrow_fun} from './components/arrow.js';
import {extA_fun} from './components/extA.js';
import {extB_fun} from './components/extB.js';
import {extC_fun} from './components/extC.js';
import {lit_fun} from './components/lit.js';
import {desA_fun} from './components/desA.js';
import {desB_fun} from './components/desB.js';
import {getCashOfBank} from './components/class.js';
import {itt_fun} from './components/iterator.js';
import {arm_fun} from './components/arm.js';
import {armstrong2} from './components/generator.js';
import {messages} from './components/chatroom.js';
import {users} from './components/chatroom.js';
import {promise} from './components/promise.js';

//const_fun();
//scope_fun();
//enhance_fun();
//arrow_fun();
//extA_fun();
//extB_fun();
//extC_fun();
//lit_fun();
//desA_fun();
//desB_fun();

//getCashOfBank();
//arm_fun();
// armstrong2();
// let m = 'music';
// let s = 'sports';
// messages(m);
// users(s);
promise();